### PR TITLE
Use user $SHELL to run commands rather than bash

### PR DESCRIPTION
**Pull request by leakec**
* Update plugin code so it works with 0.38.2.
* Using the new plugin configuration, the user can set the shell used to run the scripts. A good way to do this is by just using `$SHELL`, i.e., the user's default shell. 
  * I believe this addresses #1.

### CODE REVIEW

**Comment by leakec** [comment]
@imsnif I've also got a file to build the `multitask.wasm` when a new package is released. Relevant final commit of the working file is [here](https://github.com/leakec/multitask/commit/a8ecbd248ac4747a10c5672ebb7dbe9d02d7d12d). If you're interested, can add it to this MR.

**Comment by imsnif** [comment]
@leakec - would you like to take up maintainership of this repo? I don't want to hold you back and my hands are a bit tied with Zellij core right now...

**Comment by leakec** [comment]
@imsnif Sure, I'd be happy to.

**Comment by imsnif** [comment]
Great! Just sent you an invite. Looking forward to seeing where you take this plugin!

**Pull request merged**
